version: "3.8"

services:
  memcached:
    image: memcached
    restart: always
    expose:
      - "11211"

  yopass:
    build: .
    restart: always
    ports:
      - "80"
    environment:
      - MEMCACHED=memcached-uv5fwwvlcx1ihyxt28fpmnb0:11211
      - PORT=80
      - PRIVACY_NOTICE_URL=https://doverunner.com/privacy-policy/
      - DISABLE_FEATURES=true
    healthcheck:
      test: ["CMD", "/yopass-server", "--health-check"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    labels:
      # Middleware
      - traefik.http.middlewares.my-auth.basicauth.users=erik.pena:$2y$10$OgSzyBBH0aMBDxGF44d62OqIvH./fX3pMHwIB731B03jHsN1UjQNO
      # Router for protected path
      - traefik.http.routers.myapp-protected.rule=Host(`details.doverunner.space`) && PathPrefix(`/admin`)
      - traefik.http.routers.myapp-protected.middlewares=my-auth
      - traefik.http.routers.myapp-protected.entrypoints=websecure
      - traefik.http.routers.myapp-protected.tls=true
